package com.learningplatform.service.impl;

import com.learningplatform.service.AIService;
import org.springframework.stereotype.Service;

@Service
public class AIServiceImpl implements AIService {

    @Override
    public String generateExplanation(String topicTitle, String topicContent, String language) {
        StringBuilder explanation = new StringBuilder();
        
        explanation.append("# 🤖 AI-Powered Explanation\n\n");
        explanation.append("Based on your learning style, here's a simplified breakdown of **").append(topicTitle).append("**:\n\n");
        
        // Generate topic-specific explanation
        explanation.append(generateTopicExplanation(topicTitle, language));
        
        explanation.append("\n---\n\n");
        explanation.append("## 💡 Quick Tips\n");
        explanation.append("- Practice by writing code every day\n");
        explanation.append("- Don't memorize - understand the concepts\n");
        explanation.append("- Build small projects to reinforce learning\n");
        explanation.append("- Make mistakes - they're the best teachers!\n");
        
        explanation.append("\n---\n\n");
        explanation.append("*Generated by AI to help you learn faster. Want more details? Ask questions!\n*");
        
        return explanation.toString();
    }
    
    private String generateTopicExplanation(String topicTitle, String language) {
        String title = topicTitle.toLowerCase();
        StringBuilder sb = new StringBuilder();
        
        if (title.contains("variable")) {
            sb.append("## What are Variables?\n");
            sb.append("Variables are like **labeled boxes** that store information.\n\n");
            sb.append("**Think of it like this:**\n");
            sb.append("- Variable name = The label on the box\n");
            sb.append("- Variable value = What's inside the box\n\n");
            sb.append("**Example in ").append(getLanguageName(language)).append(":**\n");
            sb.append("```\n");
            sb.append(getVariableExample(language));
            sb.append("```\n\n");
            sb.append("**Key Points:**\n");
            sb.append("- Give variables descriptive names\n");
            sb.append("- Choose names that explain what the data represents\n");
            sb.append("- Use consistent naming patterns\n");
        } else if (title.contains("function")) {
            sb.append("## What are Functions?\n");
            sb.append("Functions are like **recipes** - they contain instructions you can reuse!\n\n");
            sb.append("**Think of it like this:**\n");
            sb.append("- You write the recipe once\n");
            sb.append("- You can follow it (call it) whenever you need it\n\n");
            sb.append("**Example in ").append(getLanguageName(language)).append(":**\n");
            sb.append("```\n");
            sb.append(getFunctionExample(language));
            sb.append("```\n\n");
            sb.append("**Why use functions?**\n");
            sb.append("- Write once, use many times\n");
            sb.append("- Makes code organized\n");
            sb.append("- Easier to fix bugs\n");
        } else if (title.contains("loop")) {
            sb.append("## What are Loops?\n");
            sb.append("Loops let you **repeat actions** without writing the same code over and over.\n\n");
            sb.append("**Think of it like this:**\n");
            sb.append("- Instead of copy-pasting code 100 times\n");
            sb.append("- You use a loop to do it automatically\n\n");
            sb.append("**Example in ").append(getLanguageName(language)).append(":**\n");
            sb.append("```\n");
            sb.append(getLoopExample(language));
            sb.append("```\n\n");
            sb.append("**Types of loops:**\n");
            sb.append("- **For loop**: When you know how many times to repeat\n");
            sb.append("- **While loop**: When you repeat until something happens\n");
        } else if (title.contains("html")) {
            sb.append("## What is HTML?\n");
            sb.append("HTML is the **skeleton** of every webpage.\n\n");
            sb.append("**Think of it like this:**\n");
            sb.append("- HTML = Structure (like bones)\n");
            sb.append("- CSS = Appearance (like skin and clothes)\n");
            sb.append("- JavaScript = Behavior (like muscles)\n\n");
            sb.append("**Example:**\n");
            sb.append("```html\n");
            sb.append("<h1>Hello World!</h1>\n");
            sb.append("<p>This is a paragraph.</p>\n");
            sb.append("```\n\n");
            sb.append("**Key Points:**\n");
            sb.append("- HTML uses tags like `<tag>` and `</tag>`\n");
            sb.append("- Everything goes between opening and closing tags\n");
            sb.append("- HTML files end with `.html`\n");
        } else if (title.contains("css") || title.contains("selector")) {
            sb.append("## What are CSS Selectors?\n");
            sb.append("Selectors tell CSS **which elements** to style.\n\n");
            sb.append("**Think of it like this:**\n");
            sb.append("- Selector = Who to style\n");
            sb.append("- Property = What to change\n");
            sb.append("- Value = How to change it\n\n");
            sb.append("**Example:**\n");
            sb.append("```css\n");
            sb.append("p { color: blue; }\n");
            sb.append(".highlight { background: yellow; }\n");
            sb.append("#header { font-size: 24px; }\n");
            sb.append("```\n\n");
            sb.append("**Types of Selectors:**\n");
            sb.append("- **Tag**: `p { }` - all paragraphs\n");
            sb.append("- **Class**: `.name { }` - elements with class=\"name\"\n");
            sb.append("- **ID**: `#name { }` - element with id=\"name\"\n");
        } else {
            // Generic explanation
            sb.append("## Understanding ").append(topicTitle).append("\n");
            sb.append("This topic covers important concepts in ").append(getLanguageName(language)).append(".\n\n");
            sb.append("**To master this:**\n");
            sb.append("1. Read the examples carefully\n");
            sb.append("2. Try changing the code yourself\n");
            sb.append("3. Build something small using these concepts\n");
            sb.append("4. Don't be afraid to experiment!\n");
        }
        
        return sb.toString();
    }
    
    private String getLanguageName(String language) {
        return switch (language.toLowerCase()) {
            case "html" -> "HTML";
            case "css" -> "CSS";
            case "javascript" -> "JavaScript";
            case "python" -> "Python";
            default -> language;
        };
    }
    
    private String getVariableExample(String language) {
        return switch (language.toLowerCase()) {
            case "javascript" -> "let name = \"Alice\";\nconst age = 25;\nlet score = 100;";
            case "python" -> "name = \"Alice\"\nage = 25\nscore = 100";
            default -> "name = \"Alice\"\nage = 25";
        };
    }
    
    private String getFunctionExample(String language) {
        return switch (language.toLowerCase()) {
            case "javascript" -> "function greet(name) {\n  return \"Hello, \" + name + \"!\";\n}\n\ngreet(\"Alice\");";
            case "python" -> "def greet(name):\n    return f\"Hello, {name}!\"\n\ngreet(\"Alice\")";
            default -> "function greet(name) {\n  return \"Hello, \" + name;\n}";
        };
    }
    
    private String getLoopExample(String language) {
        return switch (language.toLowerCase()) {
            case "javascript" -> "for (let i = 0; i < 5; i++) {\n  console.log(i);\n}";
            case "python" -> "for i in range(5):\n    print(i)";
            default -> "for i in range(5):\n    print(i)";
        };
    }
}
