-- Learning Platform Schema for H2 Database

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    username VARCHAR(100) UNIQUE NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    avatar_url VARCHAR(500),
    bio VARCHAR(5000),
    role VARCHAR(20) DEFAULT 'STUDENT',
    is_active BOOLEAN DEFAULT TRUE,
    email_verified BOOLEAN DEFAULT FALSE,
    last_login_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    description VARCHAR(5000),
    long_description VARCHAR(10000),
    category VARCHAR(100),
    difficulty VARCHAR(20) DEFAULT 'BEGINNER',
    icon_url VARCHAR(500),
    banner_url VARCHAR(500),
    is_premium BOOLEAN DEFAULT FALSE,
    price DECIMAL(10, 2) DEFAULT 0.00,
    estimated_hours DECIMAL(5, 2),
    order_index INT DEFAULT 0,
    is_published BOOLEAN DEFAULT FALSE,
    is_featured BOOLEAN DEFAULT FALSE,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lessons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    content VARCHAR(10000) NOT NULL,
    content_html VARCHAR(10000),
    code_example VARCHAR(5000),
    video_url VARCHAR(500),
    order_index INT NOT NULL,
    estimated_minutes INT,
    is_published BOOLEAN DEFAULT FALSE,
    is_premium BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(course_id, slug)
);

CREATE TABLE IF NOT EXISTS exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    lesson_id BIGINT,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(5000) NOT NULL,
    instructions VARCHAR(5000) NOT NULL,
    type VARCHAR(30) DEFAULT 'WRITE_CODE',
    starter_code VARCHAR(5000),
    solution VARCHAR(5000) NOT NULL,
    test_cases VARCHAR(5000) NOT NULL,
    difficulty VARCHAR(20) DEFAULT 'BEGINNER',
    points INT DEFAULT 10,
    hints VARCHAR(2000),
    constraints VARCHAR(1000),
    order_index INT DEFAULT 0,
    time_limit_seconds INT DEFAULT 30,
    is_published BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quizzes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    lesson_id BIGINT,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    passing_score INT DEFAULT 70,
    time_limit_minutes INT,
    shuffle_questions BOOLEAN DEFAULT FALSE,
    show_correct_answers BOOLEAN DEFAULT TRUE,
    order_index INT DEFAULT 0,
    is_published BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id BIGINT NOT NULL,
    question_text VARCHAR(2000) NOT NULL,
    question_type VARCHAR(30) DEFAULT 'MULTIPLE_CHOICE',
    points INT DEFAULT 1,
    explanation VARCHAR(2000),
    order_index INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    answer_text VARCHAR(1000) NOT NULL,
    is_correct BOOLEAN DEFAULT FALSE,
    order_index INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    lesson_id BIGINT,
    status VARCHAR(20) DEFAULT 'NOT_STARTED',
    completion_percentage DECIMAL(5, 2) DEFAULT 0.00,
    time_spent_minutes INT DEFAULT 0,
    last_accessed_at TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, lesson_id)
);

CREATE TABLE IF NOT EXISTS exercise_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    exercise_id BIGINT NOT NULL,
    user_code VARCHAR(5000),
    is_correct BOOLEAN DEFAULT FALSE,
    output VARCHAR(5000),
    error_message VARCHAR(2000),
    test_results VARCHAR(5000),
    execution_time_ms INT,
    memory_used_kb INT,
    points_earned INT DEFAULT 0,
    attempt_number INT DEFAULT 1,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quiz_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    quiz_id BIGINT NOT NULL,
    score DECIMAL(5, 2),
    total_points INT,
    earned_points INT,
    passed BOOLEAN DEFAULT FALSE,
    answers VARCHAR(5000),
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    time_taken_seconds INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    certificate_code VARCHAR(50) UNIQUE NOT NULL,
    template_id VARCHAR(50),
    recipient_name VARCHAR(255) NOT NULL,
    course_name VARCHAR(255) NOT NULL,
    issued_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expiry_date TIMESTAMP,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    metadata VARCHAR(2000),
    UNIQUE(user_id, course_id)
);

CREATE TABLE IF NOT EXISTS enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    enrolled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    completion_percentage DECIMAL(5, 2) DEFAULT 0.00,
    UNIQUE(user_id, course_id)
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(500) UNIQUE NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    revoked BOOLEAN DEFAULT FALSE
);

-- Insert sample data
INSERT INTO users (email, password_hash, username, first_name, last_name, role) 
VALUES ('admin@example.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZRGdjGj/n3.rsS/lW1pCPBJ3eGVvW', 'admin', 'Admin', 'User', 'ADMIN');

INSERT INTO courses (title, slug, description, category, difficulty, is_published, is_featured, order_index)
VALUES 
('HTML Tutorial', 'html-tutorial', 'Learn HTML from scratch', 'Web Development', 'BEGINNER', TRUE, TRUE, 1),
('CSS Tutorial', 'css-tutorial', 'Learn CSS from scratch', 'Web Development', 'BEGINNER', TRUE, TRUE, 2),
('JavaScript Tutorial', 'javascript-tutorial', 'Learn JavaScript from scratch', 'Programming', 'INTERMEDIATE', TRUE, TRUE, 3),
('Python Tutorial', 'python-tutorial', 'Learn Python from scratch', 'Programming', 'BEGINNER', TRUE, FALSE, 4);

INSERT INTO lessons (course_id, title, slug, content, order_index, is_published)
VALUES 
(1, 'HTML Introduction', 'introduction', '# HTML Introduction

HTML is the standard markup language for creating web pages.

HTML stands for Hyper Text Markup Language
HTML describes the structure of a Web page
HTML consists of a series of elements
HTML elements tell the browser how to display the content', 1, TRUE),
(1, 'HTML Elements', 'elements', '# HTML Elements

HTML elements are the building blocks of HTML pages.

An HTML element is defined by a start tag, some content, and an end tag.', 2, TRUE),
(2, 'CSS Introduction', 'introduction', '# CSS Introduction

CSS stands for Cascading Style Sheets.

CSS describes how HTML elements are to be displayed on screen, paper, or in other media.', 1, TRUE),
(3, 'JavaScript Introduction', 'introduction', '# JavaScript Introduction

JavaScript is the programming language of the Web.

JavaScript is the world most popular programming language.
This tutorial will teach you JavaScript from basic to advanced.', 1, TRUE);
